version: "2.1"
services:
  eagleun-ldap:
    image: osixia/openldap:1.1.8
    environment:
      COMPOSE_HTTP_TIMEOUT: 200
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Software Architecture"
      LDAP_DOMAIN: "arqsoft.unal.edu.co"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      #LDAP_READONLY_USER_USERNAME: "readonly"
      #LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_BACKEND: "hdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      #LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn="cn=admin,cn=config" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_DB_SYNCPROV: "binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    hostname: "arqsoft.org"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "eagleun-ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8085:80"
    links:
      - eagleun-ldap
  walt:
    build: ./walt
    environment:
      PORT: "5000"
      SHOW_URLS: 'true'
      ANA_URL: 'ana_ms'
      ANA_PORT: '9090'
      ANA_ENTRY: 'ana'
      MULAN_URL: 'mulan_ms'
      MULAN_PORT: '8080'
      MULAN_ENTRY: 'shares'
      RAPUNZEL_URL: 'rapunzel_ms'
      RAPUNZEL_PORT: '5050'
      MOANA_URL: 'moana'
      MOANA_PORT: '3000'
      MOANA_ENTRY: 'feeds'
      MERIDA_URL: 'merida'
      MERIDA_PORT: '3002'
      MERIDA_ENTRY: 'posts'
      VANELLOPE_URL: 'vanellope-ms'
      VANELLOPE_PORT: '3001'
    ports:
      - "5000:5000"
  eagleun-proxy:
    build: ./eagleun_proxy
    depends_on:
      - walt
    ports:
      - "80:80"
  mulan_ms:
    build: ./mulan 
    depends_on:
      mulan_db:
        condition: service_healthy
    ports:
      - "8080:8080"
  mulan_db:
    image: mysql
    healthcheck:
      test: "mysqlcheck -u$$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE"
      interval: 20s
      timeout: 5s
      retries: 15
    environment:
        MYSQL_DATABASE: 'mulan_db'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
    ports:
        - "3306"
    volumes:
      - my-db:/var/lib/mysql
  rapunzel_ms:
    build: ./rapunzel
    command: python -u app.py
    volumes:
      - .:/todo
    links:
      - rapunzel_db
  rapunzel_db:
    image: mongo:3.0.2
    ports:
      - "27017"
  ana_ms:
    build:
      context: ./ana
      dockerfile: './docker/Dockerfile'
    ports:
      - "9090:9090"
  mongo:
    image: mongo
    ports:
      - '27017'
  merida:
    build: ./merida
    environment:
      - MONGO_DB_URL=mongodb://mongo:27017/merida
      - WAIT_HOSTS= mongo:27017
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - "3002:3002"
  postgres:
    image: mdillon/postgis:10-alpine
    environment:
      - POSTGRES_USER=moana
      - POSTGRES_PASSWORD=yiuPh9eipiu2la9ie8gaifee
    ports:
    - '5432'
  moana:
    build: ./moana
    environment:
      - DB_HOST=postgres
      - DB_USERNAME=moana
      - DB_PASSWORD=yiuPh9eipiu2la9ie8gaifee
      - DB_DATABASE=moana
      - WAIT_HOSTS= postgres:5432
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - "3000:3000"
  vanellope-db:
    image: postgres:9.6-alpine
    ports:
      - '5432'
    environment:
      - POSTGRES_USER=usersms
      - POSTGRES_PASSWORD=yiuPh9eipiu2la9ie8gaifec
      - POSTGRES_DB=exeggcute
    volumes:
      - 'vanellope_data:/var/lib/postgresql/data'

  vanellope-ms:
    build: ./vanellope
    #normal execution without modification about database
    command: bash -c "gem uninstall bundler && gem update bundler && bundler update --bundler && bundler install && rails db:migrate && rails s -p 3001 -b '0.0.0.0'"
    #normal execution with restart database without seeds
    #command: bash -c "gem uninstall bundler && gem update bundler && bundler update --bundler && bundler install && rails db:drop && rails db:create && rails db:migrate && rails s -p 3001 -b '0.0.0.0'"
    #normal execution with restart database without seeds
    #command: bash -c "gem uninstall bundler && gem update bundler && bundler update --bundler && bundler install && rails db:drop && rails db:create && rails db:migrate && rails db:seed && rails s -p 3001 -b '0.0.0.0'"
    depends_on:
      - vanellope-db
    ports:
      - "3001:3001"

  jazmin:
    build: ./jazmin
    ports:
      - '3006:3006'

  
volumes:
  my-db:
  vanellope_data:
        
