version: "2.1"
services:
  walt:
    build: ./walt
    environment:
      PORT: "5000"
      SHOW_URLS: 'true'
      ANA_URL: 'ana_ms'
      ANA_PORT: '9090'
      ANA_ENTRY: 'ana'
      MULAN_URL: 'mulan_ms'
      MULAN_PORT: '8080'
      MULAN_ENTRY: 'shares'
      RAPUNZEL_URL: 'rapunzel_ms'
      RAPUNZEL_PORT: '5050'
      MOANA_URL: 'moana'
      MOANA_PORT: '3000'
      MOANA_ENTRY: 'feeds'
      MERIDA_URL: 'merida'
      MERIDA_PORT: '3002'
      MERIDA_ENTRY: 'posts'
      VANELLOPE_URL: 'vanellope_ms'
      VANELLOPE_PORT: '3001'
  eagleun-proxy:
    build: ./eagleun_proxy
    depends_on:
      - walt
    ports:
      - "80:80"
  mulan_ms:
    build: ./mulan 
    depends_on:
      mulan_db:
        condition: service_healthy
  mulan_db:
    image: mysql
    healthcheck:
      test: "mysqlcheck -u$$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE"
      interval: 20s
      timeout: 5s
      retries: 15
    environment:
        MYSQL_DATABASE: 'mulan_db'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
    ports:
        - "3306"
    volumes:
      - my-db:/var/lib/mysql
  rapunzel_ms:
    build: ./rapunzel
    command: python -u app.py
    volumes:
      - .:/todo
    links:
      - rapunzel_db
  rapunzel_db:
    image: mongo:3.0.2
    ports:
      - "27017"
  ana_ms:
    build:
      context: ./ana/target
      dockerfile: './ana/ana_service/Dockerfile'
  mongo:
    image: mongo
    ports:
      - '27017'
  merida:
    build: ./merida
    environment:
      - MONGO_DB_URL=mongodb://mongo:27017/merida
      - WAIT_HOSTS= mongo:27017
    links:
      - mongo
    depends_on:
      - mongo
  postgres:
    image: mdillon/postgis:10-alpine
    environment:
      - POSTGRES_USER=moana
      - POSTGRES_PASSWORD=yiuPh9eipiu2la9ie8gaifee
    ports:
    - '5432'

  moana:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_USERNAME=moana
      - DB_PASSWORD=yiuPh9eipiu2la9ie8gaifee
      - DB_DATABASE=moana
      - WAIT_HOSTS= postgres:5432
    links:
      - postgres
    depends_on:
      - postgres
  vanellope-db:
    image: postgres:9.6-alpine
    container_name: vanellopeContent
    ports:
      - '5432'
    environment:
      - POSTGRES_USER=usersms
      - POSTGRES_PASSWORD=yiuPh9eipiu2la9ie8gaifec
      - POSTGRES_DB=exeggcute
    volumes:
      - 'vanellope_data:/var/lib/postgresql/data'

  vanellope-ms:
    build: .
    #normal execution without modification about database
    command: bash -c "gem uninstall bundler && gem update bundler && bundler update --bundler && bundler install && rails db:migrate && rails s -p 3001 -b '0.0.0.0'"
    #normal execution with restart database without seeds
    #command: bash -c "gem uninstall bundler && gem update bundler && bundler update --bundler && bundler install && rails db:drop && rails db:create && rails db:migrate && rails s -p 3001 -b '0.0.0.0'"
    #normal execution with restart database without seeds
    #command: bash -c "gem uninstall bundler && gem update bundler && bundler update --bundler && bundler install && rails db:drop && rails db:create && rails db:migrate && rails db:seed && rails s -p 3001 -b '0.0.0.0'"
    depends_on:
      - vanellope-db

  
volumes:
  my-db:
  vanellope_data:
        
